apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse-csi-static-pvc-lora
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi # can be customized
  volumeName: gcs-fuse-csi-pv-lora
  storageClassName: example-storage-class
