apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse-csi-static-pvc-2
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: $5Gi # can be customized
  volumeName: gcs-fuse-csi-pv-2
  storageClassName: example-storage-class
