apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv-1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi # can be customized
  storageClassName: example-storage-class
  claimRef:
    namespace: default
    name: gcs-fuse-csi-static-pvc-1
  mountOptions:
    - implicit-dirs
    - only-dir=model1
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: sd-model-bucket