apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse-csi-static-pvc-1
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # can be customized
  volumeName: gcs-fuse-csi-pv-1
  storageClassName: example-storage-class
